### ISSUE TITLE
Progressive Web App Checklist

### ISSUE THREAD

**Issue by karanisverma** [karanisverma/karanisverma.github.io#26]
- [ ] Site is served over HTTPS
- [ ] Pages are responsive on tablets & mobile devices
- [ ] All app URLs load while offline
- [ ] Metadata provided for Add to Home screen
- [ ] First load fast even on 3G
- [ ] Site works cross-browser
- [ ] Page transitions don't feel like they block on the network
- [ ] Each page has a URL
- [ ] Schema.org metadata is provided where appropriate
- [ ] Site's content is indexed by Google
- [ ] Social metadata is provided where appropriate
- [ ] Canonical URLs are provided when necessary
- [ ] Pages use the History API
- [ ] Content doesn't jump as the page loads
- [ ] Pressing back from a detail page retains scroll position on the previous list page
- [ ] When tapped, inputs aren't obscured by the on screen keyboard
- [ ] Content is easily shareable from standalone or full screen mode
- [ ] Site is responsive across phone, tablet and desktop screen sizes
- [ ] 
- [ ] 
- [ ] 
- [ ] 
for more please refer this: https://developers.google.com/web/progressive-web-apps/checklist
